In [1]:
import pandas as pd
import numpy as np

In [6]:
# read 'temp.parquet' into df
df = pd.read_parquet('temp.parquet')

In [7]:
# drop `cumulative_sentiment`, `silly_pos`, `silly_neg`, `silly_risk`, `better_pos`, `better_neg`, `better_neutral`
df.drop(
    [
        "cumulative_sentiment",
        "silly_pos",
        "silly_neg",
        "silly_risk",
        # "better_pos",
        # "better_neg",
        # "better_neutral",
    ],
    axis=1,
    inplace=True,
)

In [8]:
# breakdown down of all the sent_labels
df["sent_label"].value_counts()

sent_label
neutral    23056
neg         6804
pos         5937
risky       3563
Name: count, dtype: int64

In [10]:
# min date and max date
df["Date"].min(), df["Date"].max()

(Timestamp('2016-01-04 09:00:00'), Timestamp('2016-04-29 16:59:00'))

In [9]:
df

,stock,Date,Open,High,Low,Close,Volume,OpenInt,better_pos,better_neg,...,title_3,title_4,title_5,text_1,text_2,text_3,text_4,text_5,cumulative_sent,sent_label
0,AAPL,2016-01-04 09:00:00,98.7787,98.7955,98.7765,98.7933,945459,0,0.100,0.025,...,Israeli Adtech Looks To Scale Up – TechCrunch,"Toyota, QNX And Others Adopt Ford’s SmartDevic...","Roku Expands Its Smart TV Platform, Will Launc...",Are Apple’s best days behind it? Is Silicon Va...,"If you have small children, pets, or drunken r...",Dennis Mitzner\nContributor\n\n\n\nDennis Mitz...,"SmartDeviceLink, Ford’s open-source technology...",If cord-cutting and streaming services are the...,72.622320,neutral
1,AAPL,2016-01-04 09:01:00,98.9509,98.9616,98.9478,98.9584,9775,0,0.099,0.037,...,The Griffin BreakSafe Brings MagSafe Back To T...,Israeli Adtech Looks To Scale Up – TechCrunch,"Toyota, QNX And Others Adopt Ford’s SmartDevic...","First tech took Manhattan, then it took Detroi...",Are Apple’s best days behind it? Is Silicon Va...,"If you have small children, pets, or drunken r...",Dennis Mitzner\nContributor\n\n\n\nDennis Mitz...,"SmartDeviceLink, Ford’s open-source technology...",71.632765,neutral
2,AAPL,2016-01-04 09:02:00,98.9753,98.9818,98.9743,98.9809,105876,0,0.099,0.037,...,The Griffin BreakSafe Brings MagSafe Back To T...,Israeli Adtech Looks To Scale Up – TechCrunch,"Toyota, QNX And Others Adopt Ford’s SmartDevic...","First tech took Manhattan, then it took Detroi...",Are Apple’s best days behind it? Is Silicon Va...,"If you have small children, pets, or drunken r...",Dennis Mitzner\nContributor\n\n\n\nDennis Mitz...,"SmartDeviceLink, Ford’s open-source technology...",71.632765,neutral
3,AAPL,2016-01-04 09:03:00,98.9894,99.0004,98.9878,98.9988,41552,0,0.099,0.037,...,The Griffin BreakSafe Brings MagSafe Back To T...,Israeli Adtech Looks To Scale Up – TechCrunch,"Toyota, QNX And Others Adopt Ford’s SmartDevic...","First tech took Manhattan, then it took Detroi...",Are Apple’s best days behind it? Is Silicon Va...,"If you have small children, pets, or drunken r...",Dennis Mitzner\nContributor\n\n\n\nDennis Mitz...,"SmartDeviceLink, Ford’s open-source technology...",71.632765,neutral
4,AAPL,2016-01-04 09:04:00,98.8496,98.8648,98.8477,98.8629,101203,0,0.099,0.037,...,The Griffin BreakSafe Brings MagSafe Back To T...,Israeli Adtech Looks To Scale Up – TechCrunch,"Toyota, QNX And Others Adopt Ford’s SmartDevic...","First tech took Manhattan, then it took Detroi...",Are Apple’s best days behind it? Is Silicon Va...,"If you have small children, pets, or drunken r...",Dennis Mitzner\nContributor\n\n\n\nDennis Mitz...,"SmartDeviceLink, Ford’s open-source technology...",71.632765,neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39355,AAPL,2016-04-29 16:55:00,90.6509,90.6535,90.6498,90.6524,145212,0,0.049,0.044,...,Phil Schiller takes to Twitter to remind every...,"Review: On ‘Views,’ Drake Is Still His Own Genre",Why is Facebook doing so well?,"Today, Drake's new album and long-awaited hype...",The first Monday of May is fast approaching. I...,Last night a single tweet on everyone’s favori...,Drake’s career has been built on collapsing wa...,A version of this essay was originally publish...,37.967914,neutral
39356,AAPL,2016-04-29 16:56:00,90.6151,90.6252,90.6082,90.6182,382031,0,0.049,0.044,...,Phil Schiller takes to Twitter to remind every...,"Review: On ‘Views,’ Drake Is Still His Own Genre",Why is Facebook doing so well?,"Today, Drake's new album and long-awaited hype...",The first Monday of May is fast approaching. I...,Last night a single tweet on everyone’s favori...,Drake’s career has been built on collapsing wa...,A version of this essay was originally publish...,37.967914,neutral
39357,AAPL,2016-04-29 16:57:00,90.6879,90.7023,90.6845,90.6989,24298,0,0.049,0.044,...,Phil Schiller takes to Twitter to remind every...,"Review: On ‘Views,’ Drake Is Still His Own Genre",Why is Facebook doing so well?,"Today, Drake's new album and long-awaited hype...",The first Monday of May is fast approaching. I...,Last night a single tweet on everyone’s favori...,Drake’s career has been built on collapsing wa...,A version of this essay was originally publish...,37.967914,neutral
39358,AAPL,2016-04-29 16:58:00,90.7103,90.7190,90.7076,90.7163,64553,0,0.049,0.044,...,Phil Schiller takes to Twitter to remind every...,"Review: On ‘Views,’ Drake Is Still His Own Genre",Why is Facebook doing so well?,"Today, Drake's new album and long-awaited hype...",The first Monday of May is fast approaching. I...,Last night a single tweet on everyone’s favori...,Drake’s career has been built on collapsing wa...,A version of this essay was originally publish...,37.967914,neutral
39359,AAPL,2016-04-29 16:59:00,90.7302,90.7488,90.7292,90.7478,12619,0,0.049,0.044,...,Phil Schiller takes to Twitter to remind every...,"Review: On ‘Views,’ Drake Is Still His Own Genre",Why is Facebook doing so well?,"Today, Drake's new album and long-awaited hype...",The first Monday of May is fast approaching. I...,Last night a single tweet on everyone’s favori...,Drake’s career has been built on collapsing wa...,A version of this essay was originally publish...,37.967914,neutral

In [39]:
# write to json, list of objects
# format 'Date' column as string
df['Date'] = df['Date'].astype(str)
df.to_json('temp.json', orient='records')

In [6]:
df

,stock,Date,Open,High,Low,Close,Volume,OpenInt,cumulative_sentiment,silly_pos,silly_neg,silly_risk,better_pos,better_neg,better_neutral
0,AAPL,2016-01-04 09:00:00,98.7787,98.7955,98.7765,98.7933,945459,0,6.263,0.019355,0.019355,0.009677,0.100,0.025,0.875
1,AAPL,2016-01-04 09:01:00,98.9509,98.9616,98.9478,98.9584,9775,0,6.338,0.007117,0.005338,0.014235,0.099,0.037,0.864
2,AAPL,2016-01-04 09:02:00,98.9753,98.9818,98.9743,98.9809,105876,0,6.338,0.007117,0.005338,0.014235,0.099,0.037,0.864
3,AAPL,2016-01-04 09:03:00,98.9894,99.0004,98.9878,98.9988,41552,0,6.338,0.007117,0.005338,0.014235,0.099,0.037,0.864
4,AAPL,2016-01-04 09:04:00,98.8496,98.8648,98.8477,98.8629,101203,0,6.338,0.007117,0.005338,0.014235,0.099,0.037,0.864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32665,AAPL,2016-04-29 16:26:00,90.3918,90.4096,90.3916,90.4094,113973,0,95.822,0.013423,0.000000,0.013423,0.049,0.044,0.906
32666,AAPL,2016-04-29 16:27:00,90.3883,90.4021,90.3851,90.3989,336531,0,95.822,0.013423,0.000000,0.013423,0.049,0.044,0.906
32667,AAPL,2016-04-29 16:28:00,90.4870,90.5017,90.4846,90.4993,17618,0,95.822,0.013423,0.000000,0.013423,0.049,0.044,0.906
32668,AAPL,2016-04-29 16:29:00,90.3874,90.3950,90.3827,90.3903,29529,0,95.822,0.013423,0.000000,0.013423,0.049,0.044,0.906
32669,AAPL,2016-04-29 16:30:00,90.3295,90.3432,90.3294,90.3431,446014,0,95.822,0.013423,0.000000,0.013423,0.049,0.044,0.906